source 'https://rubygems.org'

ruby '>= 3.1'

gem 'sinatra', '~> 4.0'
gem 'rackup', '~> 2.1'
gem 'puma', '~> 6.4'

group :test do
  gem 'minitest', '~> 5.20'
  gem 'rack-test', '~> 2.1'
  gem 'rake', '~> 13.0'
end
